<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<InvariantGlobalization>true</InvariantGlobalization>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.19"/>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2"/>
		<PackageReference Include="Microsoft.Azure.SignalR" Version="1.30.0" />
		<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="8.0.0" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
      <Content Include=".github\workflows\ci.yml" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="src\Hubs\" />
      <Folder Include="src\Services\Interfaces\" />
    </ItemGroup>

</Project>
